function stateVector = createStateVector(state)

stateVector = [ ...
    state.rssi; ...
    state.sinr; ...
    state.delay; ...
    state.loss; ...
    state.cpuMEC1; ...
    state.cpuMEC2; ...
    state.memoryMEC1; ...
    state.memoryMEC2; ...
    state.buffer; ...
    state.freezeTime; ...
    state.qoe; ...
    state.connectedMEC ...
    ];

end